title: Madai Urteaga
description: # Add your description here
logo: /assets/img/your-photo.jpg
remote_theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
markdown: kramdown
