remote_theme: mmistakes/minimal-mistakes@4.24.0
markdown: kramdown
plugins:
  - jekyll-include-cache

logo: /assets/img/IMG_4764ed.jpg

name: Madai Urteaga
title: Postdoctoral Fellow, University of Notre Dame
description: >
  I study the political economy of agricultural policy, state building, and rural mobilization in Latin America.
